# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_suggest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggest',
        ),
    ]
